### PR TITLE
Improve POSIX-compatibility of picom-trans

### PR DESCRIPTION
**Pull request by subnut**
On OpenBSD

### CODE REVIEW

**Comment by yshui** [comment]
@subnut would this command still work: `picom-trans -c -5 -s`?

**Comment by subnut** [comment]
Yes, it works.

It waits for the user to select a window, and then reduces the opacity by 5%

That's what it should do, right?

**Comment by subnut** [comment]
@yshui I have a question -

Say, you open a new window. Now, you run 
```
picom-trans -c -t
```
What happens in your PC?  
Does the window become transparent? (ie. opacity automatically set to zero)

**Comment by yshui** [comment]
@subnut looks like this script doesn't handle missing opacity argument correctly, which is an existing bug. this PR looks good, thanks.

**Pull request merged**
