### PR TITLE
Add foreground blurring

### PR DESCRIPTION
**Pull request by rajansaini691**
Discussion started from issue #489. 

The end goal is to create a "focus mode" that blurs inactive windows. This is very much still a work in progress.

So far I have given windows a `blur_foreground` option and have successfully gotten it to work. Still need to:
 * Apply the blur when and only when the window is inactive and focus mode is enabled
 * Get a `--focus-mode` command line option

I am worried about strong coupling between modes and behaviors, which is preventing me from making progress. Ideally, the logic should be placed at a higher level rather than in `paint_all_new`. Does anyone more familiar with the codebase have any recommendations?

### CODE REVIEW

**Comment by tryone144** [comment]
> * Apply the blur when and only when the window is inactive and focus mode is enabled

If I am not mistaken, similar logic to opacity is needed that updates the `blur_foreground` flag of a window. Code for that should be in [win.c](https://github.com/yshui/picom/blob/2451c2153958e3771de715a9f15bc43c71e8f757/src/win.c#L910).

> * Get a `--focus-mode` command line option

I was thinking `--blur-inactive` might be more descriptive as `--focus-mode` is kind of vague on what it actually does. You can find the config options in [config.c](https://github.com/yshui/picom/blob/2451c2153958e3771de715a9f15bc43c71e8f757/src/config.h#L70) with actual parsing in [config_libconfig.c](https://github.com/yshui/picom/blob/2451c2153958e3771de715a9f15bc43c71e8f757/src/config_libconfig.c#L295). Command line options are declared and parsed in [options.c](https://github.com/yshui/picom/blob/2451c2153958e3771de715a9f15bc43c71e8f757/src/options.c#L511).

> I am worried about strong coupling between modes and behaviors, which is preventing me from making progress. Ideally, the logic should be placed at a higher level rather than in `paint_all_new`. Does anyone more familiar with the codebase have any recommendations?

Yes, `paint_all_new()` should just be concerned about applying the blur if the window's foreground should be blurred. Updating that flag might be best done in `win_on_factor_change()` (see above).

Regarding the style "errors": You can either configure your editor to use the provided clang-format style file or run `clang-format -style=file` on the source file manually.

**Comment by yshui** [comment]
> `--blur-inactive`

`inactive-blur` is probably more consistent with the current option names. Also a `inactive-blur-exclude` would be a good to have.

> Ideally, the logic should be placed at a higher level rather than in paint_all_new.

I think it's fine for it to be in `paint_all_new`. May I ask why you think otherwise?

**Comment by rajansaini691** [comment]
@tryone144 and @yshui thanks for the feedback! That sounds good, I'll add an option called `inactive-blur`. 

The reason I was reluctant to put the logic in `paint_all_new` is because I thought it might be more maintainable to decouple foreground blurring from a specific option. This way, in the future, others could add other options that blur a window's foreground without touching `paint_all_new`. However, if you're okay with the strong coupling, that makes my end much easier.

**Comment by rajansaini691** [comment]
Jus added an option and logic for blurring inactive. It seems to work, though it slows down switches between panes and occasionally does not blur my browser (qutebrowser) when it unfocuses.

**Comment by yshui** [comment]
@rajansaini691 Ah, I see what you mean.

Yes, I agree with @tryone144, `paint_all_new` should just check a flag set on the window to determine if the blur should be applied, instead of checking the option. And that window flag can be set in `win_on_factor_change`.

**Comment by yshui** [comment]
BTW, @tryone144, do you have access to the CircleCI?

**Comment by tryone144** [comment]
> Edit: Also, sorry, what would the behavior of `inactive-blur-exclude` be?

Analogous to the other `*-exclude` options, windows that match the rules in there should not be affected by the foreground blur when inactive.

> BTW, @tryone144, do you have access to the CircleCI? e.g. can you restart CI jobs, etc.

Seems so, I just restarted the failed `test` job.

**Comment by rajansaini691** [comment]
I stopped work on this issue, but there shouldn't be a lot of work left if anyone wants to pick it up :)

**Comment by yshui** [comment]
Closed due to inactivity and the PR can't be merged in its current form.

**Pull request closed without merging**
