### PR TITLE
Improve usage message printing

### PR DESCRIPTION
**Pull request by yshui**

### CODE REVIEW

**Comment by tryone144** [comment]
Thanks for simplifying the options interface! This has been bugging me for a while. :sweat_smile: 

---

I have some experimental code locally that uses an `enum` for the option id's / shortcodes instead of relying on the magic numbers. Having that would be a nice addition when extending/restructuring the options.

However, I am still struggling to find a nice way of merging the general handling in options.c and config_libconfig.c. Having the same logic in two places is kind of not nice. The first attempt using macros has turned out to be even messier...

**Comment by yshui** [comment]
@tryone144 can i see your first attempt?

**Comment by tryone144** [comment]
> @tryone144 can i see your first attempt?

I am currently away from my main machine on a spotty (at best) internet connection. I will push the partially working WIP code as soon as I get back.
Code-reviews might be delayed as well. Unless you are in a hurry to merge the latest PRs, I recon I'd get these done around the next weekend.

**Comment by tryone144** [comment]
> @tryone144 can i see your first attempt?

See [this](https://github.com/tryone144/picom/tree/config-refactor) branch. This is out-of-date with `next` and might not compile.
Notable changes are:
- `enum` over all configuration options in `options_defs.h` to get rid of manually assigned ids.
- do all range-checking and clamping in `options.c` and only there.
- preprocessor macros for handling int, long, double, bool, and string arguments in `options_macros.h`. The idea was to define appropriate macros for getopt and libconfig and then include this header as the single source of truth (I think the approach is called *X Macros*). Ended up being quite messy in the current state and not really a step forward; particularly due to the edge cases and special handling some options require.

**Comment by yshui** [comment]
@tryone144 I've looked at your attempt. Nice idea but it did end up being quite messy. I think we can merge this PR as an incremental improvement. Eventually I think it might be a good idea to generate the config code from a python script or something.

**Pull request merged**
