### PR TITLE
Rounded corner cleanup

### PR DESCRIPTION
**Pull request by yshui**

### CODE REVIEW

**Comment by yshui** [comment]
ping #361 and #229

**Comment by jslick** [comment]
Hi, is this branch a WIP?  I'm having trouble building it.
```
[16/30] Compiling C object src/picom.p/backend_backend.c.o
FAILED: src/picom.p/backend_backend.c.o
cc -Isrc/picom.p -Isrc -I../src -Isubprojects/test.h -I../subprojects/test.h -I/usr/include/pixman-1 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 '-DCOMPTON_VERSION="vgit-2c696"' -DNDEBUG -D_GNU_SOURCE -DHAS_STDC_PREDEF_H -Wall -Wcast-function-type -Wignored-qualifiers -Wmissing-parameter-type -Wnonnull -Wshadow -Wno-type-limits -Wold-style-declaration -Woverride-init -Wsign-compare -Wtype-limits -Wuninitialized -Wshift-negative-value -Wunused-but-set-parameter -Wunused-parameter -Wimplicit-fallthrough -Wno-missing-braces -Wconversion -Wempty-body -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -DCONFIG_LIBCONFIG -DCONFIG_REGEX_PCRE -DCONFIG_REGEX_PCRE_JIT -DCONFIG_OPENGL -DGL_GLEXT_PROTOTYPES -DCONFIG_DBUS -DHAS_INOTIFY -MD -MQ src/picom.p/backend_backend.c.o -MF src/picom.p/backend_backend.c.o.d -o src/picom.p/backend_backend.c.o -c ../src/backend/backend.c
../src/backend/backend.c: In function ‘paint_all_new’:
../src/backend/backend.c:152:57: warning: passing argument 3 of ‘ps->backend_data->ops->compose’ makes integer from pointer without a cast [-Wint-conversion]
  152 |   ps->backend_data->ops->compose(ps->backend_data, t, ps->root_image, 0, 0,
      |                                                       ~~^~~~~~~~~~~~
      |                                                         |
      |                                                         void *
../src/backend/backend.c:152:57: note: expected ‘int’ but argument is of type ‘void *’
../src/backend/backend.c:152:3: error: too many arguments to function ‘ps->backend_data->ops->compose’
  152 |   ps->backend_data->ops->compose(ps->backend_data, t, ps->root_image, 0, 0,
      |   ^~
```

**Comment by tryone144** [comment]
> Hi, is this branch a WIP? I'm having trouble building it.

Yup, see https://github.com/yshui/picom/pull/493#issuecomment-694162356.

> Thanks for your contribution. The `round` branch is still WIP so it's not expected to compile.

**Comment by subnut** [comment]
Any ETA to get it done? I mean that ibhagwan's fork is working fine, isn't it? So why not here?

**Comment by RandomExplosion** [comment]
@yshui what's the current status on this PR?

**Comment by tryone144** [comment]
This PR has been closed in favour of #551, #558, and #614 for the legacy backends. Rounded corners should already work there.
The implementation of rounded corners for the experimental-backends is tracked in https://github.com/yshui/picom/pull/658 (currently WIP).

**Pull request closed without merging**
