### PR TITLE
Correct shadows for shaped and rounded windows

### PR DESCRIPTION
**Pull request by yshui**
Example: 

Based on #881 This is only implemented for glx, not xrender.

### CODE REVIEW

**Comment by nawuko** [comment]
This will be an awesome feature :+1: 

Dunno if it is ready for testing, shadow branch (https://github.com/yshui/picom/pull/882/commits/0777f0781b1f3af6305a3b05caa34028c212a7b9) dosen't draw any shadows, i get following error:
```picom[863747]: [ 27.08.2022 16:09:16.603 gl_create_shader ERROR ] GLX error at line 61: GL_INVALID_OPERATION```

Nvidia Closed Source Driver
Driver Version: 515.65.01
CUDA Version: 11.7
Backend: glx

**Comment by yshui** [comment]
@nawuko can you [record a trace](https://github.com/yshui/picom/wiki/Reporting-issues#capture-a-trace)?

**Comment by yshui** [comment]
@nawuko also, is there more in the log?

**Comment by doums** [comment]
Hello, I observe the same error, no shadow is rendered.

Arch Linux 5.19.4-arch1-1
Xorg
XMonad (No DE)
Nvidia proprietary driver: [nvidia](https://archlinux.org/packages/extra/x86_64/nvidia/) and [nvidia-utils](https://archlinux.org/packages/extra/x86_64/nvidia-utils/)
Driver Version: 515.65.01
Backend: glx

you can find my config here -> https://github.com/doums/dotfiles/blob/master/.config/picom.conf

I tried to generate a trace, sadly I got an error with apitrace preventing to start picom.

**Comment by frebib** [comment]
I can also reproduce this with `nvidia` proprietary drivers and `glx` backend. Here's an `apitrace`
(I also ran into the same libc issue with apitrace as @doums. I recompiled it with this patch applied: https://github.com/apitrace/apitrace/commit/d28a980802ad48568c87da02d630c8babfe163bb)
[picom.trace.tar.gz](https://github.com/yshui/picom/files/9456836/picom.trace.tar.gz)
I had to compress it so github would accept upload 😒

**Comment by yshui** [comment]
@frebib Thanks for the trace! I have fixed the problem, apparently a typo... :cry:

**Comment by nawuko** [comment]
Can confirm, its working for me now on nvidia :+1:

**Comment by doums** [comment]
image
I confirm too, thx for this PR.

**Comment by frebib** [comment]
Works great for me too. Thanks for the quick fix!
It's so good to finally get this functionality without the performance penalty that other patches with this functionality incur.
Great work 🎉

**Comment by frebib** [comment]
Out of curiosity, should this fix the shadow/blur behind windows with strange bounding boxes like the context menus in Firefox? I still see a small ~5-6 pixel border of shadow/blur even with this patch and I'm not sure if that's intentional. I have `shadow-ignore-shaped=false` and `detect-rounded-corners=true` although I'm not sure they'd help towards that

**Comment by yshui** [comment]
@frebib unfortunately no, firefox's context menu doesn't use the X shape extension, it just has parts of it being completely transparent. that's why there are gaps. 

i am considering adding an option to use windows' alpha channels as their bounding shape, which would solve this.

**Comment by yshui** [comment]
I wonder how many people has already tested this branch?

**Comment by frebib** [comment]
Second that. I have this running on two computers with one running proprietary nvidia drivers and the other i915 iGPU and it's running great

**Comment by yshui** [comment]
OK, let's make the call and merge this without @tryone144's review.

@tryone144 please still do have a look at this when you find some time! i still want to hear your input.

**Comment by Monsterovich** [comment]
Wtf happened to the shadows. They are ugly now.

Now:
Снимок экрана_2022-09-18_01-04-23
Before:
Снимок экрана_2022-09-18_01-05-18

**Comment by yshui** [comment]
@Monsterovich I was trying out using dual kawase blur for shadow, I changed it back to gaussian now.

**Comment by doums** [comment]
I was observing the same as @Monsterovich, but playing a bit with shadow values fixed the issue, but yea shadow was rendered differently.

**Comment by Monsterovich** [comment]
> I was observing the same as @Monsterovich, but playing a bit with shadow values fixed the issue, but yea shadow was rendered differently.

How did you fix it?

**Comment by doums** [comment]
Using these values
```
shadow-radius = 11;
shadow-offset-x = -16;
shadow-offset-y = -12;
```
at least for me it kinda fix what we observe on your first screenshot
but it's definitively not good as before

**Comment by Monsterovich** [comment]
> @Monsterovich it should be back to what it used to be on latest git.

I don't see any new commits in the "next" branch. Have you pushed them yet?

**Comment by yshui** [comment]
@Monsterovich oops, I didn't. :sweat_smile: Sorry about that!

**Comment by Monsterovich** [comment]
@yshui Thank you! Could you please take a look at  https://github.com/yshui/picom/issues/863? This issue is really annoying.

**Comment by Monsterovich** [comment]
@yshui There is also a bit of a problem with the new changes. The underside of the shadow is smooth as it was before. But the sides are not smooth. Why is that? Without zooming in it looks like graphical artifacts.

изображение

**Comment by Monsterovich** [comment]
@yshui Can you suggest a fix for the ugly effect with the shadows? https://github.com/yshui/picom/pull/882#issuecomment-1272167342?

**Pull request merged**
