### PR TITLE
Martin/nvidia fixes

### PR DESCRIPTION
**Pull request by sandsmark**
Applies the fixes suggested by kwand et al in https://github.com/yshui/picom/issues/592

Just smoketested it for about a day and seems to work fine, but I haven't done any in-depth testing to test the efficacy of the improvements.

### CODE REVIEW

**Comment by sandsmark** [comment]
CircleCI doesn't allow me to see what happened.

**Comment by morgoth6** [comment]
Take a look at #597 Currently testing with vsync enabled and without both __GL_MaxFramesAllowed and __GL_YIELD set.

**Comment by sandsmark** [comment]
not sure if glFlush really matters in a compositor, though it doesn't hurt I guess.

**Comment by kwand** [comment]
Deepest apologies, but after doing some profiling with Nsight Systems, I'm no longer sure if this does anything at all. (I haven't profiled the exact changes as proposed here, but I suspect the results might not be quite different from profiling with just `__GL_MaxFramesAllowed` set).

Please see https://github.com/yshui/picom/issues/592#issuecomment-803253918.

**Comment by yshui** [comment]
Suppressed by #641

**Pull request closed without merging**
