### PR TITLE
Update picom.sample.conf

### PR DESCRIPTION
**Pull request by tonijarjour**
-For the settings, I put everything as default. You should change them to what you know is appropriate. 
-No comments or descriptions because I feel people can read the manual (`man picom` or `picom -h`).
-Removed the deprecated stuff.

### CODE REVIEW

**Comment by yshui** [comment]
> For the settings, I put everything as default. You should change them to what you know is appropriate.

It is debatable whether the sample config should have all of the default values. I opt to not make changes that aren't clear improvements.

> No comments or descriptions because I feel people can read the manual (man picom or picom -h).

Comments are helpful. Although it's true people can read the manuals, having the comments there is definitely more convenient. 

> Removed the deprecated stuff.

This one is good, can you change the PR to only include this?

**Comment by tonijarjour** [comment]
Alright its just deprecated stuff removed. But would you consider reorganizing the file into the sections I made?

**Comment by yshui** [comment]
@tonijarjour Thanks, merged.

Isn't the sample config already in sections?

**Comment by tonijarjour** [comment]
Oh I mean that there should be an "Opacity/Dimming" section, and I would put all of the following under it:
```
inactive-opacity
frame-opacity
active-opacity
inactive-opacity-override
inactive-dim
inactive-dim-fixed
mark-wmwin-focused
mark-ovredir-focused
no-ewmh-fullscreen
use-ewmh-active-win
detect-client-opacity
detect-client-leader
detect-transient
unredir-if-possible
unredir-if-possible-delay
unredir-if-possible-exclude
focus-exclude
opacity-rule
invert-color-include
max-brightness
transparent-clipping
```
The checks for whether a window is focused are just being used to change opacity or brightness. So if someone doesn't use opacity or dimming, all of these settings are irrelevant to them. Unless of course they have some utility beyond this.

The other stuff:
```
detect-rounded-corners
```
Should go under Shadow because it is just dealing with drawing rounded corner shadows.
```
resize-damage
```
I put under blur because the description said "Primarily used to fix the line corruption issues of blur"

**Comment by mitchell-gil96** [comment]
First time configurations and users would have to switch back and forth between an editor and a terminal running man or picom -h. That's two separate areas to search for a simple config option each line. It is much more intuitive to have the explanation per line in the config file, easily accessible. The current way the config file is structured with the comments is the way other established projects like grub have their configs setup.

**Comment by mighty9245** [comment]
@mitchell-gil96, having two windows placed side-by-side is too hard nowadays.

**Comment by yump** [comment]
```
no-ewmh-fullscreen

unredir-if-possible
unredir-if-possible-delay
unredir-if-possible-exclude
```

These things should not be part of an Opacity/Dimming section.  Unredirection of fullscreen windows is for performance and latency.  The fact that unredirection disables effects is incidental.

**Pull request merged**
