### PR TITLE
More delayed event handlings

### PR DESCRIPTION
**Pull request by yshui**
Part of the configure notify handling which requires querying the X
server, has been moved into the X critical section.

There is more to come.

### CODE REVIEW

**Comment by yshui** [comment]
This together should eliminate all calls to `wid_get_text_prop` outside of the critical section, and then we can merge #516

**Comment by tryone144** [comment]
While rebasing #479 I managed to trigger an assertion failure with the testcase for issue #394: `picom: ../src/win.c:1065: win_on_win_size_change: Assertion 'w->state == WSTATE_UNMAPPED' failed.`

```
gef➤  bt
#0  0x00007f5d8188c355 in raise () from /usr/lib/libc.so.6
#1  0x00007f5d81875853 in abort () from /usr/lib/libc.so.6
#2  0x00007f5d81875727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f5d81884936 in __assert_fail () from /usr/lib/libc.so.6
#4  0x000055a74bf199df in win_on_win_size_change (ps=0x55a74c84d8c0, w=0x55a74c859e50) at ../src/win.c:1065
#5  0x000055a74bf17c7b in win_process_update_flags (ps=0x55a74c84d8c0, w=0x55a74c859e50) at ../src/win.c:421
#6  0x000055a74bf12115 in refresh_windows (ps=0x55a74c84d8c0) at ../src/picom.c:1326
#7  0x000055a74bf1237c in handle_pending_updates (loop=0x7f5d81e59720, ps=0x55a74c84d8c0) at ../src/picom.c:1374
#8  0x000055a74bf12522 in draw_callback_impl (loop=0x7f5d81e59720, ps=0x55a74c84d8c0, revents=0x2000) at ../src/picom.c:1401
#9  0x000055a74bf1294a in draw_callback (loop=0x7f5d81e59720, w=0x55a74c84d980, revents=0x2000) at ../src/picom.c:1489
#10 0x00007f5d81e4d033 in ev_invoke_pending () from /usr/lib/libev.so.4
#11 0x00007f5d81e50902 in ev_run () from /usr/lib/libev.so.4
#12 0x000055a74bf15c03 in session_run (ps=0x55a74c84d8c0) at ../src/picom.c:2356
#13 0x000055a74bf15f02 in main (argc=0x8, argv=0x7ffd8639a2f8) at ../src/picom.c:2458
gef➤  list
1060            if (w->state == WSTATE_MAPPED || w->state == WSTATE_MAPPING ||
1061                w->state == WSTATE_FADING) {
1062                    win_set_flags(w, WIN_FLAGS_IMAGES_STALE);
1063                    ps->pending_updates = true;
1064            } else {
1065                    assert(w->state == WSTATE_UNMAPPED);
1066            }
1067            free_paint(ps, &w->shadow_paint);
1068    }
1069
gef➤  p w->state
$1 = WSTATE_DESTROYING
```

I'll push the changes shortly for you to test. It seems commit a099678664c17d2ac58fdd05c1939813e74c452a allows `win_on_win_size_change()` to be called on destroyed/destroying windows. I don't think forcefully clearing all kind of flags for windows to be destroyed is the right way to fix either this, nor the shadow issue.

**Comment by yshui** [comment]
@tryone144 
> I don't think forcefully clearing all kind of flags for windows to be destroyed is the right way to fix either this, nor the shadow issue.

Why is that ?

**Comment by tryone144** [comment]
> @tryone144
> 
> > I don't think forcefully clearing all kind of flags for windows to be destroyed is the right way to fix either this, nor the shadow issue.
> 
> Why is that ?

I might have confused some of this with unmapped windows (instead of destroyed).
It is correct that we can't get stuff like pixmap, size/shape, or properties from a window that has already been destroyed. Since we don't update those the moment they are changed, we have to ignore those updates when we keep our window around for fading out. This might mean we use "outdated" information, but the only alternative would be to update them immediately (which we don't want due to possible race conditions). Clearing the related flags should be the cleaner solution than to explicitly check in the respective update functions.

I am not so sure about the shadow however, since actually (re-)creating the stale shadow image seems to work even for destroyed windows, it's just the flag updating that doesn't (or more specifically, setting `SHADOW_NONE` is done regardless in `win_release_shadow()`, but it can't be cleared once the new shadow has been created in `win_bind_shadow()`).

If I am not mistaken, the window will still have its `w->shadow` flag set to `true` while having no shadow image. I haven't tested yet, if this can actually happen since the original issue only had problems with updating an existing shadow. Do you know if it's still possible for a window to get a shadow (`w->shadow = true` in `win_set_shadow()`), being destroyed (`destroy_win_start()`), and then being handled in `handle_pending_updates()` and rendered? If this can't happen, just clearing the stale flags should be enough. I might be wrong with my reasoning here though.

**Comment by yshui** [comment]
> since actually (re-)creating the stale shadow image seems to work even for destroyed windows

This is true, I don't know if this is really necessary though. If recreating a shadow image for a destroyed window is what we should do, we could relax the flag update rule.

> if it's still possible for a window to get a shadow (`w->shadow = true` in `win_set_shadow()`), being destroyed (`destroy_win_start()`), and then being handled in `handle_pending_updates()` and rendered?

If we clear flags in `destroy_win_start`, then it should go through `handle_pending_updates` without being touched. A destroyed window can still be rendered if fading is enabled.

**Comment by yshui** [comment]
ping @tryone144

**Comment by tryone144** [comment]
> If recreating a shadow image for a destroyed window is what we should do, we could relax the flag update rule.

I don't think we have to. The time the window will be still visible by fading out is usually very short.

> > if it's still possible for a window to get a shadow (`w->shadow = true` in `win_set_shadow()`), being destroyed (`destroy_win_start()`), and then being handled in `handle_pending_updates()` and rendered?
> 
> If we clear flags in `destroy_win_start`, then it should go through `handle_pending_updates` without being touched. A destroyed window can still be rendered if fading is enabled.

This is what I am more concerned and not entirely sure of:
1) Window has no shadow (`w->shadow = false`, `w->flags & WIN_FLAGS_SHADOW_NONE != 0`)
2) Window should get a shadow, either through dbus (`win_set_shadow_force()`), or some other way (I haven't checked all calls to `win_on_factor_change()` yet. A change by any of the normal events seems to be honored in `handle_pending_updates()` and therefore should not be a problem). So `w->shadow = true`, `(w->flags & WIN_FLAGS_SHADOW_NONE != 0) && (w->flags & WIN_FLAGS_SHADOW_STALE != 0)` in `win_set_shadow()`.
3) Window is destroyed before the next draw-call (and handling of pending updates). So `w->shadow = true`, `w->flags & WIN_FLAGS_SHADOW_NONE != 0` since we clear `WIN_FLAGS_SHADOW_STALE` in `destroy_win_start()`. Window is now fading out (can't receive new events but is still rendered).
4) Next draw call with pending updates while window is not finished fading. We will try to render the shadow in `paint_all_new()` since `w->shadow = true`, but we don't have a shadow image (hence `w->flags & WIN_FLAGS_SHADOW_NONE != 0`) and trigger the assertion.

Am I missing something here? Normal property updates should not trigger the addition of a shadow to a window in state `WSTATE_DESTROYING` since we cleared the update flags and therefore do not touch the window in `handle_pending_updates()`. But there might be other places that could do that, e.g. a dbus call to `win_set_shadow_force()`.

**Comment by yshui** [comment]
@tryone144 That's a very good point.

But that's not that hard to fix, right? We just need to push handling of `win_set_shadow_force` into `handle_pending_updates` as well, i.e. only set flags in `win_set_shadow_force` and actually update `shadow` later.

I think that should fix the problem. Am I missing anything?

**Comment by tryone144** [comment]
I think we should be good once all updates to a window's state (`shadow`, etc.) are only handled in the critical section of `handle_pending_updates()`. The recent PRs made this a whole lot easier to trace. Clearing the flags will then stop updating destroyed windows and let them fade out with whatever their last known (valid) state was.

For a start, we should trace all callers of `win_on_factor_change()` outside `handle_pending_updates()`. `win_set_shadow_force()` doesn't actually call `win_on_factor_change()`. But I haven't yet found the time to manually trace all possible state changes.

**Comment by yshui** [comment]
> For a start, we should trace all callers of `win_on_factor_change()` outside `handle_pending_updates()`. 

I just made a tool to help me trace this kind of stuff. And I believe there are none. All calls to `win_on_factor_change` go through `handle_pending_updates` now.

**Comment by yshui** [comment]
@tryone144 `win_set_shadow_force` calls `win_determine_shadow`, which is what sets `shadow` and the stale flag.

**Comment by yshui** [comment]
@tryone144 I guess it was indeed not covered by my tests, as I didn't try setting the flags with dbus.

**Comment by yshui** [comment]
So I checked again. Ignoring function pointers, the only path from `cdbus_process` (the entry point for dbus messages) to `win_on_factor_change` is through `win_set_focused_force`.

And from `cdbus_process` to `win_determine_shadow`, there is `win_set_focused_force` and `win_set_shadow_force`

**Comment by tryone144** [comment]
@yshui Nice! :+1: 

It should suffice to set `WIN_FLAGS_FACTOR_CHANGED` in `win_set_focused_force` and `win_set_shadow_force` to trigger the update in `handle_pending_updates()` instead of right there.

**Pull request merged**
