### PR TITLE
Rounded border for new glx backend

### PR DESCRIPTION
**Pull request by yshui**

### CODE REVIEW

**Comment by tryone144** [comment]
The `#define` here: https://github.com/yshui/picom/blob/1edf0de055e81f5c4a997bc0b6cf8e7d2e45d7da/src/backend/gl/gl_common.h#L99-L100 is not used anywhere and still uses the non-refactored `unifm_*` names. It could be removed in the clean-up commit as well.

The changes look okay to me. However, the border color is incorrectly detected on my i3 setup. With https://github.com/yshui/picom/pull/761/commits/1edf0de055e81f5c4a997bc0b6cf8e7d2e45d7da, `read_pixel` returns non-sensical values for the windows; seemingly random, but consistent over picom's runtime. Prior to that commit, `read_pixel` always returns the same sane but incorrect color.

**Comment by yshui** [comment]
@tryone144 interesting. I tested on awesomeWM and the pixel value is correct. Prior to 1edf0de `read_pixel` is reading from the screen instead of reading from the window.

**Comment by tryone144** [comment]
Reading from screen makes sense for the color values prior to the fix. I am not quite sure how exactly the window texture looks in i3 when deciding on the border color, but the returned pixel values look like uninitialized memory.
BTW: Is this supposed to work with i3's "frame windows"? Otherwise, the pixel coordinates might be outside the window dimensions.

**Comment by yshui** [comment]
`read_pixel` is suppose to read a pixel in the window's border so picom knows what color to draw. that's why it needs to read from the window texture, not the screen.

the window texture is usually of the WM window, aka the frame window. can you do a apitrace to see what the window texture looks like? thanks.

**Comment by tryone144** [comment]
Here the apitrace: [rounded-border-glx-trace.zip](https://github.com/yshui/picom/files/7919239/rounded-border-glx-trace.zip)
In this run, the drawn border is bright red (in contrast to the blue-grey borders of i3).

I've found multiple `GL_INVALID_FRAMEBUFFER_OPERATION` errors after calls that looks like `read_pixel()`.
Just for reference: I am running on a *GeForce GTX 1070* with `nvidia-495.46-10`. This might be a driver quirk like https://github.com/yshui/picom/pull/648. Can't test on my Intel system right now.

**Comment by yshui** [comment]
@tryone144 something is weird with that apitrace. :thinking: everything is heavily down scaled for some reason.


as you can see the content of the texture is downscaled and only occupies the lower left corner of the texture.

**Comment by yshui** [comment]
@tryone144 something is odd with that apitrace. 

the content of the framebuffer appears to be downscaled when i try to replay it here, like this:

a

**Comment by tryone144** [comment]
That's interesting. The base-dimensions of that image are correct. Whatever causes the framebuffer to be only one fourth of the actual size…?
However, the image you see matches my screen (although too small — it fills both my screens locally at 3840x1200px).

I've just noticed that apitrace segfaults at the end of its execution when capturing a trace. I also cannot properly replay my trace.

**Comment by tryone144** [comment]
I did some more testing:
- `gl_check_fb_complete(GL_READ_FRAMEBUFFER);` after binding the texture raises `GL_FRAMEBUFFER_UNSUPPORTED`
- `gl_check_err();` after reading the pixel raises `GL_INVALID_FRAMEBUFFER_OPERATION`

I highly suspect the (proprietary) nvidia driver to not like the format of our GLX texture.

**Comment by yshui** [comment]
On second thought, why am I reading the pixel at all... I could just sample it in GLSL.

**Comment by tryone144** [comment]
> I could just sample it in shader

IIRC, this is what the original code did, anyway.
We don't need the border color in xrender, since reading the pixel value and drawing a border has a bigger overhead than in gl — if I am not mistaken.

**Comment by yshui** [comment]
Yep, I was dumb lol.

**Comment by yshui** [comment]
@tryone144 can you test it again? thanks.

**Review by tryone144 — APPROVED** [review]
The latest changes produce correctly colored borders on my system. :+1:

**Pull request merged**
